blender.exe --background --python flaw_generator.py -- \
--displace 0.5 \
--faces-abs 1 1 \
--face-prop \
--gaps 0 0 \
--hole-fixed 20 \
--meta \
--root ./meshes/pillows_eval \
--splits 0 \
--test-samples 0 \
--train-samples 3